### ISSUE TITLE
Flag low coordination numbers for lanthanide/alkaline/alkaline earth

### ISSUE THREAD

**Issue by kjappelbaum** [kjappelbaum/mofchecker#50]
## Feature description

Lanthanides like to have many neighbors and we now many instances in CoRE where they have surprisingly few neighbors. 

## Implementation idea

```python
def _check_metal_coordination(site, cn: int) -> bool:
    # Lanthanides like to have many neighbors
    # Low coordinatio number is usually only
    # possible with really bulky ligands
    # for this reason, a Lanthanide with low
    # coordination number, e.g., <= 4 can be considered "interesting"
    if site.specie.is_lanthanide():
        if cn <= 4:
            return True

    # Also for the alkaline/alkaline earth metals,
    # I would find a low coordination number surprising
    elif site.specie.is_alkali() or site.specie.is_alkaline():
        if cn <= 2:
            return True

    return False
```

**Comment by arosen93** [comment]
If I recall correctly, I think many of the instances of the low coordination numbers in the CoRE MOF database for the lanthanides are cases where terminal O were removed as "solvent" even though they might be oxos or hydroxyl groups. For instance, the uranyl node has the motif O=U=O, but it's easy to accidentally flag those O atoms as water and remove them.

The check for the alkali(ne earth) metals is also important but probably a bit tougher. [Li-exchanged MFU-4l](https://www.sciencedirect.com/science/article/abs/pii/S1387181115001730) for instance is three-coordinate, and a quick ConQuest search of the CSD MOF subset points to a lot of hits with low-coordinate alkali(ne earth) metals. Whether those are all physical or not though, I'm not entirely sure.

**Comment by kjappelbaum** [comment]
>If I recall correctly, I think many of the instances of the low coordination numbers in the CoRE MOF database for the lanthanides are cases where terminal O were removed as "solvent" even though they might be oxos or hydroxyl groups. For instance, the uranyl node has the motif O=U=O, but it's easy to accidentally flag those O atoms as water and remove them.

Indeed, we're currently working on a ML-based approach to find those + charged cases, this model flagged a lot of lanthanides that were low coordinated and which I found suspicious. Our main challenge is currently to systematically assess if those cases are physical or not (rather than relying on my guts ...). 

But I guess you're write one should remove this check for now.

**Comment by arosen93** [comment]
Sweet! Best of luck to you and the team on that! I think the ML-based approach is probably the smartest. You'll surely flag them pretty effectively that way. This is all going to be great for the community because we need some good tools out there for this, even if they'll never be perfect.

My gut instinct is that the simple heuristic you had/have here for low coordination number checker is probably perfectly suitable for the lanthanides/actinides in most cases. I saw that max(coord. num.) was set to 4 for the alkali metals in the commit I accessed, which made me think of the Li-MFU-4l, so I figured I'd just share that counter-example.
